blank_issues_enabled: true
contact_links:
  - name: Obsidian forum
    url: https://forum.obsidian.md/
    about: Use the official forum for general Obsidian questions that are not specific to Aoi Tori.
